### ISSUE TITLE
Bugfixes for Lessons

### ISSUE THREAD

**Issue by pjz1** [williams-cs/swell#86]
These things might not be working because of changes to SWELL itself

- [x]  Lesson 2 Checkpoint 1: does not continue even after happy face is produced

- [x]  Lesson 2 Checkpoint 3: does not continue after happy and sad faces are drawn
- [x] Lesson 2 Checkpoint 4: when variable is changed to b and cool face is drawn, lesson does not continue
- [x] Lesson 3 Checkpoint 4: c == "happy" and smiley face prints but lesson does not continue

**Comment by dbarowy** [comment]
I fixed all of the issues with checkpoints in lessons 1 and 2.  @pzhao1799 could you have a look at lesson 3?  There were three main sources of breakage in the first two lessons:

1. We apparently changed the meaning of the `.name` field in the `EmojiEffect` class.  It now always returns `emoji`.  Instead, I added a `.type` field which will return what we want (e.g., `pirate` or `happy`).  Many of the completion checks in lessons 1 and 2 were failing because of this change.
2. Because we added named arguments, many of the regular expressions in completion checks also fail in their presence.  This is most acute when using direct manipulation, as DM always inserts names.  I updated such regular expressions to optionally allow named arguments.  This mostly consisted of changing the part of the regexp that was looking for an argument, something like `,\s*[1-9][0-9]*`, to something more like `,\s*(x\s*=\s*)?[1-9][0-9]*`.
3. Because we eliminated the `;` sequence operator from the syntax (we now depend on seeing newlines), a lot of the starter code broke.  I went through and just deleted these.

Finally, I noticed that named arguments really do make our instructions clearer, so I also modified many of the instructions to refer to specific variables by name instead of having to describe their positions.  If you see opportunities like this, please use variable names in instructions.

**Comment by dbarowy** [comment]
Fixed in e81dfab148c08084618ea4a35469e15111b2ccc4.
